title: Qvistary's Blog
description: > 
permalink: ':title/'
baseurl: 
url: "https//qvistary.github.io"


author: Qvistary 
author-img: qvistary.jpg 
about-author: Let life be beautiful like summer flowers and death like autumn leaves. 


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
